### ISSUE TITLE
Sierra Support

### ISSUE THREAD

**Issue by mdl00** [schreiberstein/lucidagrandeelcapitan#8]
Sorry for being impatient, as macOS Sierra was only announced yesterday, but are you planning on making a version compatible with it? I tried running the El Capitan version and it says the font is incompatible.

**Comment by schreiberstein** [comment]
I am not planning to do that, but I'll have a chat with my partner and see whether or not he is even interested in it anymore. As you can guess, the transition from El Capitan to Sierra is probably not going to fix any issues that existed previously. It'll just make things more complicated. Apple doesn't want users to customize their own systems - theming is virtually impossible. I personally like OS X' new font-face (San Francisco) and the new UI design, except for these obnoxious blue folder icons... Cheers!

**Comment by vista980622** [comment]
I am the co-creator of LucidaGrandeYosemite and LucidaGrandeElCapitan. I am currently looking into adding support for macOS Sierra.

**Comment by mdl00** [comment]
Great!

**Comment by LumingYin** [comment]
## Update:

[LucidaGrandeYosemite](https://github.com/schreiberstein/lucidagrandeyosemite) and [LucidaGrandeElCapitan](https://github.com/schreiberstein/lucidagrandeelcapitan) are now better than ever - they have been rewritten in Cocoa as a native macOS app - [macOSLucidaGrande](https://github.com/HiKay/macOSLucidaGrande). Best of all, it now supports **macOS Sierra**, OS X El Capitan and OS X Yosemite and no longer require administrator privilege!
- Easily switch between Lucida Grande and San Francisco as your Mac's system font on macOS Sierra (10.12) and OS X El Capitan (10.11)
- Easily switch between Lucida Grande and Helvetica Neue as your Mac's system font on OS X Yosemite (10.10)
- Simple and safe, with no administrator privilege required

![](https://raw.githubusercontent.com/HiKay/macOSLucidaGrande/master/Screenshot/Screenshot.png)

**[Download macOSLucidaGrande](http://hikay.github.io/app/lucidagrande/index.html)**

**[What should I do If I am unable to open macOSLucidaGrande?](FAQ.md)**

**Comment by mdl00** [comment]
Are you affiliated with the original developer?

**Comment by LumingYin** [comment]
To mdl00:

Yes. We worked closely together for developing the original LucidaGrandeYosemite and LucidaGrandeElCapitan. You can verify this by at [this project's landing page](https://github.com/schreiberstein/lucidagrandeelcapitan):

> **Check out the updated version for MacOS made by my partner Kay Yin:** https://github.com/HiKay/macOSLucidaGrande

**Comment by mdl00** [comment]
Awesome, thanks!

**Comment by smasetty** [comment]
Hi Guys, 

Any reviews/feedback on HiKay's app? I am planning to give this a shot on Sierra Mac OS.  Please let me know

Sharat
